services:
  node:
    image: node:22
    volumes:
      - "./api:/var/www"  
      - "./database:/var/www/database"
    ports:
      - "8081:3000"
    depends_on:
      mongo:
        condition: service_healthy
    command: bash -c "cd /var/www && npm install && npm install -g pm2 && pm2 start startup.json --name API --no-daemon"
    environment:
      - URL_MONGO=mongodb://api:docker1234@mongo
      - SECRET_KEY=RXCT34ZE5GFDSFD756

  mongo:
    image: mongo:8.2
    volumes:
      - "./mongo/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=api
      - MONGO_INITDB_ROOT_PASSWORD=docker1234
    healthcheck:                         
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s 
      
    